### ISSUE TITLE
Include model name in "The ModelDefinition instance is not valid. Details: name is not unique."

### ISSUE THREAD

**Issue by bajtos** [strongloop/strong-arc#562]
Modify the code creating models to include model name in the error mesage printed when an attempt to create a duplicate model is detected.

At the moment, the message says "The `ModelDefinition` instance is not valid. Details: `name` is not unique.". This is not enough information to identify the problematic model in the situation when multiple models are being created as part of model discovery.

Loosely related to #354.

**Comment by bajtos** [comment]
This will be fixed by https://github.com/strongloop/loopback-datasource-juggler/pull/389

![screen shot 2015-01-12 at 15 04 28](https://cloud.githubusercontent.com/assets/1140553/5703885/614fc6aa-9a6c-11e4-89d7-b4ef47c0e320.png)

**Comment by bajtos** [comment]
The fix was released in `loopback-datasource-juggler@2.14.0`.

@cgole please verify. You need to run `npm install loopback-datasource-juggler` inside Arc to get the fixed version. If you are using builds from our CI, then please consult @rmg how to get a version that includes updated juggler.

**Comment by rmg** [comment]
strong-arc doesn't used fixed versions, AFAIK, so just doing `npm install -g strongloop` from staging _should_ get the latest and greatest of both arc and loopback-datasource-juggler.

**Comment by cgole** [comment]
juggler version in my app is 2.14.6.  I am still getting the error so it must be from my global install which has different versions of juggler. 
This is from the latest strongloop install from staging. 

strong-pm/node_modules/loopback-datasource-juggler/package.json:3:  "version": "2.14.6",
loopback-workspace/node_modules/loopback-datasource-juggler/package.json:3:  "version": "1.7.1",
generator-loopback/node_modules/loopback-workspace/node_modules/loopback-datasource-juggler/package.json:3:  "version": "2.14.6",
strong-arc/node_modules/loopback-datasource-juggler/package.json:3:  "version": "2.10.3",

**Comment by bajtos** [comment]
This is the problematic line:

```
strong-arc/node_modules/loopback-datasource-juggler/package.json:3:  "version": "2.10.3",
```

**Comment by bajtos** [comment]
And it looks like a problem of Arc's package json, which says

```
"loopback-datasource-juggler": "~2.10.3",
```

**Comment by bajtos** [comment]
I have landed #931, the problem should be fixed now. @cgole please verify.

**Comment by cgole** [comment]
verified
